import pkg from "@prisma/client";
import { randomBytes, scryptSync } from "node:crypto";

const {
  ConversationKind,
  DiscussionKind,
  GroupStatus,
  MembershipRole,
  MembershipStatus,
  OutcomeType,
  PrismaClient,
  RequestStatus,
} = pkg;

const prisma = new PrismaClient();

const SEEDED_PASSWORD = "Test123";

function hashPassword(password) {
  const salt = randomBytes(16).toString("hex");
  const hash = scryptSync(password, salt, 64).toString("hex");
  return `${salt}:${hash}`;
}

const sharedPasswordHash = hashPassword(SEEDED_PASSWORD);

const sharedAvatarUrl = "https://i.pravatar.cc/240?img=24";

const coreUsers = [
  {
    id: "temp-user",
    email: "owner@fourhops.local",
    name: "Ranjeet Mehra",
    isAdmin: true,
    headline: "Founder @ LedgerSpring",
    linkedinUrl: "https://www.linkedin.com/in/ranjeetmehra",
    whatsappNumber: "+48 512 440 118",
    phoneNumber: "+48 512 440 118",
    workEmail: "ranjeet@ledgerspring.com",
    personalEmail: "ranjeet.mehra@gmail.com",
  },
  {
    id: "guest-user",
    email: "guest@fourhops.local",
    name: "Elena Fischer",
    headline: "CFO Talent Advisor @ Northlane Capital",
    linkedinUrl: "https://www.linkedin.com/in/elenafischer",
    whatsappNumber: "+49 151 2664 9081",
    phoneNumber: "+49 151 2664 9081",
    workEmail: "elena@northlane.capital",
    personalEmail: "elena.fischer@proton.me",
  },
  {
    id: "maya-founder",
    email: "maya@fourhops.local",
    name: "Maya Chen",
    headline: "Founder @ RelayStack",
    linkedinUrl: "https://www.linkedin.com/in/mayachen-relaystack",
    whatsappNumber: "+44 7700 900 114",
    phoneNumber: "+44 7700 900 114",
    workEmail: "maya@relaystack.io",
    personalEmail: "mayachen@hey.com",
  },
  {
    id: "leo-operator",
    email: "leo@fourhops.local",
    name: "Leo Grant",
    headline: "VP Operations @ Copperline",
    linkedinUrl: "https://www.linkedin.com/in/leogrant-ops",
    whatsappNumber: "+49 176 4452 1184",
    phoneNumber: "+49 176 4452 1184",
    workEmail: "leo@copperline.eu",
    personalEmail: "leo.grant@icloud.com",
  },
  {
    id: "nina-investor",
    email: "nina@fourhops.local",
    name: "Nina Duarte",
    headline: "Partner @ Vela Ventures",
    linkedinUrl: "https://www.linkedin.com/in/ninaduarte",
    whatsappNumber: "+351 912 844 220",
    phoneNumber: "+351 912 844 220",
    workEmail: "nina@velaventures.com",
    personalEmail: "nina.duarte@gmail.com",
  },
  {
    id: "alex-growth",
    email: "alex@fourhops.local",
    name: "Alex Morgan",
    headline: "Growth Lead @ Signal Foundry",
    linkedinUrl: "https://www.linkedin.com/in/alexmorgan-growth",
    whatsappNumber: "+33 6 52 81 14 77",
    phoneNumber: "+33 6 52 81 14 77",
    workEmail: "alex@signalfoundry.co",
    personalEmail: "alex.morgan@pm.me",
  },
  {
    id: "sara-product",
    email: "sara@fourhops.local",
    name: "Sara Holt",
    headline: "Chief Product Officer @ FathomOS",
    linkedinUrl: "https://www.linkedin.com/in/saraholt-product",
    whatsappNumber: "+45 31 54 72 60",
    phoneNumber: "+45 31 54 72 60",
    workEmail: "sara@fathomos.com",
    personalEmail: "sara.holt@outlook.com",
  },
  {
    id: "omar-fintech",
    email: "omar@fourhops.local",
    name: "Omar Rahim",
    headline: "COO @ Ternary Pay",
    linkedinUrl: "https://www.linkedin.com/in/omarrahim",
    whatsappNumber: "+971 50 887 4112",
    phoneNumber: "+971 50 887 4112",
    workEmail: "omar@ternarypay.com",
    personalEmail: "omar.rahim@gmail.com",
  },
  {
    id: "julia-ops",
    email: "julia@fourhops.local",
    name: "Julia Weber",
    headline: "Operating Partner @ Eastfield Studio",
    linkedinUrl: "https://www.linkedin.com/in/juliaweber-ops",
    whatsappNumber: "+49 171 301 6628",
    phoneNumber: "+49 171 301 6628",
    workEmail: "julia@eastfield.studio",
    personalEmail: "j.weber@fastmail.com",
  },
  {
    id: "eva-talent",
    email: "eva@fourhops.local",
    name: "Eva Novak",
    headline: "Talent Partner @ Portside",
    linkedinUrl: "https://www.linkedin.com/in/evanovak",
    whatsappNumber: "+420 724 881 552",
    phoneNumber: "+420 724 881 552",
    workEmail: "eva@portside.team",
    personalEmail: "eva.novak@seznam.cz",
  },
  {
    id: "tom-data",
    email: "tom@fourhops.local",
    name: "Tom Becker",
    headline: "Head of Data @ PatternGrid",
    linkedinUrl: "https://www.linkedin.com/in/tombecker-data",
    whatsappNumber: "+31 6 1814 5532",
    phoneNumber: "+31 6 1814 5532",
    workEmail: "tom@patterngrid.ai",
    personalEmail: "tom.becker@gmail.com",
  },
  {
    id: "ria-b2b",
    email: "ria@fourhops.local",
    name: "Ria Sethi",
    headline: "Revenue Operator @ Meridian Cloud",
    linkedinUrl: "https://www.linkedin.com/in/riasethi",
    whatsappNumber: "+91 98102 44716",
    phoneNumber: "+91 98102 44716",
    workEmail: "ria@meridiancloud.io",
    personalEmail: "ria.sethi@gmail.com",
  },
  {
    id: "liam-ai",
    email: "liam@fourhops.local",
    name: "Liam Park",
    headline: "AI Product Lead @ ClinFlow",
    linkedinUrl: "https://www.linkedin.com/in/liampark-ai",
    whatsappNumber: "+1 415 555 0147",
    phoneNumber: "+1 415 555 0147",
    workEmail: "liam@clinflow.ai",
    personalEmail: "liam.park@gmail.com",
  },
  {
    id: "zoe-health",
    email: "zoe@fourhops.local",
    name: "Zoe Kim",
    headline: "Founder @ MedSignal AI",
    linkedinUrl: "https://www.linkedin.com/in/zoekim-health",
    whatsappNumber: "+82 10-4421-8806",
    phoneNumber: "+82 10-4421-8806",
    workEmail: "zoe@medsignal.ai",
    personalEmail: "zoe.kim@icloud.com",
  },
  {
    id: "noah-marketplace",
    email: "noah@fourhops.local",
    name: "Noah Blake",
    headline: "Founder @ Parcel Loop",
    linkedinUrl: "https://www.linkedin.com/in/noahblake-loop",
    whatsappNumber: "+1 646 555 0181",
    phoneNumber: "+1 646 555 0181",
    workEmail: "noah@parcelloop.com",
    personalEmail: "noah.blake@proton.me",
  },
  {
    id: "claire-clinical",
    email: "claire@fourhops.local",
    name: "Claire Morgan",
    headline: "Chief Clinical Officer @ Helix Bio",
    linkedinUrl: "https://www.linkedin.com/in/clairemorgan-clinical",
    whatsappNumber: "+44 7700 901 223",
    phoneNumber: "+44 7700 901 223",
    workEmail: "claire@helixbio.com",
    personalEmail: "claire.morgan@proton.me",
  },
  {
    id: "priya-reg",
    email: "priya@fourhops.local",
    name: "Priya Shah",
    headline: "VP Regulatory @ NorthBridge Therapeutics",
    linkedinUrl: "https://www.linkedin.com/in/priyashah-regulatory",
    whatsappNumber: "+44 7700 901 224",
    phoneNumber: "+44 7700 901 224",
    workEmail: "priya@northbridgetx.com",
    personalEmail: "priya.shah@gmail.com",
  },
  {
    id: "sofia-bd",
    email: "sofia@fourhops.local",
    name: "Sofia Alvarez",
    headline: "VP Business Development @ Aurelia Pharma",
    linkedinUrl: "https://www.linkedin.com/in/sofia-alvarez-bd",
    whatsappNumber: "+34 610 441 882",
    phoneNumber: "+34 610 441 882",
    workEmail: "sofia@aureliapharma.com",
    personalEmail: "sofia.alvarez@icloud.com",
  },
  {
    id: "hannah-board",
    email: "hannah@fourhops.local",
    name: "Hannah Brooks",
    headline: "CEO @ Vantage Biologics",
    linkedinUrl: "https://www.linkedin.com/in/hannahbrooks-biotech",
    whatsappNumber: "+1 617 555 0194",
    phoneNumber: "+1 617 555 0194",
    workEmail: "hannah@vantagebio.com",
    personalEmail: "hannah.brooks@gmail.com",
  },
  {
    id: "lucia-medical",
    email: "lucia@fourhops.local",
    name: "Lucia Romano",
    headline: "CMO @ Arcadia Therapeutics",
    linkedinUrl: "https://www.linkedin.com/in/luciaromano-medical",
    whatsappNumber: "+39 347 881 2204",
    phoneNumber: "+39 347 881 2204",
    workEmail: "lucia@arcadiatx.com",
    personalEmail: "lucia.romano@fastmail.com",
  },
  {
    id: "elise-strategy",
    email: "elise@fourhops.local",
    name: "Elise Laurent",
    headline: "Board Partner @ Meridian Life Sciences",
    linkedinUrl: "https://www.linkedin.com/in/eliselaurent-life-sciences",
    whatsappNumber: "+33 6 44 82 91 15",
    phoneNumber: "+33 6 44 82 91 15",
    workEmail: "elise@meridianls.com",
    personalEmail: "elise.laurent@proton.me",
  },
  {
    id: "nadia-portfolio",
    email: "nadia@fourhops.local",
    name: "Nadia Petrov",
    headline: "Portfolio Strategy Lead @ Elevate BioVentures",
    linkedinUrl: "https://www.linkedin.com/in/nadiapetrov-life-sciences",
    whatsappNumber: "+49 151 442 881 22",
    phoneNumber: "+49 151 442 881 22",
    workEmail: "nadia@elevatebio.vc",
    personalEmail: "nadia.petrov@proton.me",
  },
  {
    id: "marta-qa",
    email: "marta@fourhops.local",
    name: "Marta Zielinska",
    headline: "VP Quality @ Arclight Biologics",
    linkedinUrl: "https://www.linkedin.com/in/marta-zielinska-quality",
    whatsappNumber: "+48 516 220 901",
    phoneNumber: "+48 516 220 901",
    workEmail: "marta@arclightbio.com",
    personalEmail: "marta.zielinska@gmail.com",
  },
  {
    id: "isabel-translational",
    email: "isabel@fourhops.local",
    name: "Isabel Costa",
    headline: "Head of Translational Medicine @ Vireo Therapeutics",
    linkedinUrl: "https://www.linkedin.com/in/isabelcosta-translational",
    whatsappNumber: "+351 912 440 116",
    phoneNumber: "+351 912 440 116",
    workEmail: "isabel@vireotx.com",
    personalEmail: "isabel.costa@icloud.com",
  },
  {
    id: "freya-finance",
    email: "freya@fourhops.local",
    name: "Freya Nielsen",
    headline: "CFO @ Nordica Biotech",
    linkedinUrl: "https://www.linkedin.com/in/freya-nielsen-biotech",
    whatsappNumber: "+45 28 44 19 77",
    phoneNumber: "+45 28 44 19 77",
    workEmail: "freya@nordicabio.com",
    personalEmail: "freya.nielsen@proton.me",
  },
  {
    id: "julia-clinops",
    email: "julia.clinops@fourhops.local",
    name: "Julia Schneider",
    headline: "VP Clinical Operations @ Cadenza Bio",
    linkedinUrl: "https://www.linkedin.com/in/julia-schneider-clinops",
    whatsappNumber: "+49 170 441 3381",
    phoneNumber: "+49 170 441 3381",
    workEmail: "julia@cadenzabio.com",
    personalEmail: "julia.schneider@fastmail.com",
  },
  {
    id: "amira-medaffairs",
    email: "amira@fourhops.local",
    name: "Amira El-Sayed",
    headline: "Medical Affairs Lead @ Solenne Pharma",
    linkedinUrl: "https://www.linkedin.com/in/amira-elsayed-medical",
    whatsappNumber: "+31 6 44 18 92 20",
    phoneNumber: "+31 6 44 18 92 20",
    workEmail: "amira@solennepharma.com",
    personalEmail: "amira.elsayed@gmail.com",
  },
  {
    id: "helena-corpdev",
    email: "helena@fourhops.local",
    name: "Helena Berg",
    headline: "Corporate Development Director @ Althea Bio",
    linkedinUrl: "https://www.linkedin.com/in/helenaberg-corpdev",
    whatsappNumber: "+46 70 441 9921",
    phoneNumber: "+46 70 441 9921",
    workEmail: "helena@altheabio.com",
    personalEmail: "helena.berg@icloud.com",
  },
  {
    id: "rebeca-ra",
    email: "rebeca@fourhops.local",
    name: "Rebeca Navarro",
    headline: "Regulatory Affairs Director @ Novarex Therapeutics",
    linkedinUrl: "https://www.linkedin.com/in/rebeca-navarro-regulatory",
    whatsappNumber: "+34 611 003 228",
    phoneNumber: "+34 611 003 228",
    workEmail: "rebeca@novarextx.com",
    personalEmail: "rebeca.navarro@proton.me",
  },
  {
    id: "camille-investor",
    email: "camille@fourhops.local",
    name: "Camille Renaud",
    headline: "Partner @ Helix Capital",
    linkedinUrl: "https://www.linkedin.com/in/camille-renaud-healthcare",
    whatsappNumber: "+33 6 88 22 94 11",
    phoneNumber: "+33 6 88 22 94 11",
    workEmail: "camille@helixcap.com",
    personalEmail: "camille.renaud@proton.me",
  },
  {
    id: "naomi-biometrics",
    email: "naomi@fourhops.local",
    name: "Naomi Clarke",
    headline: "Head of Biometrics @ Orion Bio",
    linkedinUrl: "https://www.linkedin.com/in/naomi-clarke-biometrics",
    whatsappNumber: "+44 7711 440 228",
    phoneNumber: "+44 7711 440 228",
    workEmail: "naomi@orionbio.com",
    personalEmail: "naomi.clarke@gmail.com",
  },
  {
    id: "karin-pipeline",
    email: "karin@fourhops.local",
    name: "Karin Holm",
    headline: "Pipeline Strategy Lead @ Vanta Bio",
    linkedinUrl: "https://www.linkedin.com/in/karin-holm-pipeline",
    whatsappNumber: "+46 73 118 4402",
    phoneNumber: "+46 73 118 4402",
    workEmail: "karin@vantabio.com",
    personalEmail: "karin.holm@proton.me",
  },
  {
    id: "aline-ceo",
    email: "aline@fourhops.local",
    name: "Aline Moreau",
    headline: "CEO @ Novella Therapeutics",
    linkedinUrl: "https://www.linkedin.com/in/aline-moreau-biotech",
    whatsappNumber: "+33 6 72 11 84 03",
    phoneNumber: "+33 6 72 11 84 03",
    workEmail: "aline@novellatx.com",
    personalEmail: "aline.moreau@icloud.com",
  },
  {
    id: "signe-alliance",
    email: "signe@fourhops.local",
    name: "Signe Larsen",
    headline: "Alliance Management Lead @ Axion Pharma",
    linkedinUrl: "https://www.linkedin.com/in/signe-larsen-alliance",
    whatsappNumber: "+45 31 88 20 44",
    phoneNumber: "+45 31 88 20 44",
    workEmail: "signe@axionpharma.com",
    personalEmail: "signe.larsen@fastmail.com",
  },
  {
    id: "anna-digital",
    email: "anna@fourhops.local",
    name: "Anna Kowalski",
    headline: "Chief Digital Officer @ Novagen Pharma",
    linkedinUrl: "https://www.linkedin.com/in/annakowalski-digital",
    whatsappNumber: "+48 601 221 774",
    phoneNumber: "+48 601 221 774",
    workEmail: "anna@novagenpharma.com",
    personalEmail: "anna.kowalski@fastmail.com",
  },
  {
    id: "marcus-data-pharma",
    email: "marcus@fourhops.local",
    name: "Marcus Reid",
    headline: "VP Data Strategy @ Helix Therapeutics",
    linkedinUrl: "https://www.linkedin.com/in/marcusreid-data",
    whatsappNumber: "+44 7700 901 771",
    phoneNumber: "+44 7700 901 771",
    workEmail: "marcus@helixtherapeutics.com",
    personalEmail: "marcus.reid@proton.me",
  },
  {
    id: "sophie-ai-pharma",
    email: "sophie@fourhops.local",
    name: "Sophie Lambert",
    headline: "SVP AI Transformation @ Ardent Biopharma",
    linkedinUrl: "https://www.linkedin.com/in/sophielambert-ai",
    whatsappNumber: "+33 6 88 24 17 11",
    phoneNumber: "+33 6 88 24 17 11",
    workEmail: "sophie@ardentbio.com",
    personalEmail: "sophie.lambert@gmail.com",
  },
  {
    id: "daniel-gxp",
    email: "daniel@fourhops.local",
    name: "Daniel Mercer",
    headline: "VP GxP Systems @ Meridian Pharma",
    linkedinUrl: "https://www.linkedin.com/in/danielmercer-gxp",
    whatsappNumber: "+1 617 555 0197",
    phoneNumber: "+1 617 555 0197",
    workEmail: "daniel@meridianpharma.com",
    personalEmail: "daniel.mercer@hey.com",
  },
  {
    id: "isabella-ops-pharma",
    email: "isabella@fourhops.local",
    name: "Isabella Conti",
    headline: "COO @ NeutraBio",
    linkedinUrl: "https://www.linkedin.com/in/isabellaconti-ops",
    whatsappNumber: "+39 347 991 2254",
    phoneNumber: "+39 347 991 2254",
    workEmail: "isabella@neutrabio.com",
    personalEmail: "isabella.conti@icloud.com",
  },
  {
    id: "jonas-platform",
    email: "jonas@fourhops.local",
    name: "Jonas Berg",
    headline: "Head of Clinical Data Platforms @ Northstar Bio",
    linkedinUrl: "https://www.linkedin.com/in/jonasberg-platform",
    whatsappNumber: "+46 70 445 1882",
    phoneNumber: "+46 70 445 1882",
    workEmail: "jonas@northstarbio.se",
    personalEmail: "jonas.berg@proton.me",
  },
  {
    id: "meera-regops",
    email: "meera@fourhops.local",
    name: "Meera Patel",
    headline: "VP Regulatory Operations @ Calyx Therapeutics",
    linkedinUrl: "https://www.linkedin.com/in/meerapatel-regops",
    whatsappNumber: "+44 7700 901 772",
    phoneNumber: "+44 7700 901 772",
    workEmail: "meera@calyxtx.com",
    personalEmail: "meera.patel@gmail.com",
  },
  {
    id: "victor-commercial",
    email: "victor@fourhops.local",
    name: "Victor Stein",
    headline: "Chief Commercial Excellence Officer @ Aureon Pharma",
    linkedinUrl: "https://www.linkedin.com/in/victorstein-commercial",
    whatsappNumber: "+49 171 992 6117",
    phoneNumber: "+49 171 992 6117",
    workEmail: "victor@aureonpharma.com",
    personalEmail: "victor.stein@outlook.com",
  },
  {
    id: "laura-enterprise-data",
    email: "laura@fourhops.local",
    name: "Laura Jensen",
    headline: "VP Enterprise Data @ Solace BioSystems",
    linkedinUrl: "https://www.linkedin.com/in/laurajensen-data",
    whatsappNumber: "+45 31 88 72 04",
    phoneNumber: "+45 31 88 72 04",
    workEmail: "laura@solacebio.com",
    personalEmail: "laura.jensen@pm.me",
  },
  {
    id: "peter-digital-brand",
    email: "peter@fourhops.local",
    name: "Peter Novak",
    headline: "SVP Digital Platforms @ BioNova Therapeutics",
    linkedinUrl: "https://www.linkedin.com/in/peternovak-digital",
    whatsappNumber: "+420 724 110 882",
    phoneNumber: "+420 724 110 882",
    workEmail: "peter@bionovatx.com",
    personalEmail: "peter.novak@gmail.com",
  },
  {
    id: "owner-property",
    email: "charlotte@fourhops.local",
    name: "Charlotte Reed",
    headline: "Managing Director @ Northline Property",
    linkedinUrl: "https://www.linkedin.com/in/charlotte-reed-property",
    whatsappNumber: "+44 7701 112 223",
    phoneNumber: "+44 7701 112 223",
    workEmail: "charlotte@northlineproperty.com",
    personalEmail: "charlotte.reed@fastmail.com",
  },
  {
    id: "sam-asset",
    email: "sam@fourhops.local",
    name: "Samir Patel",
    headline: "Asset Manager @ Bridgeway Residential",
    linkedinUrl: "https://www.linkedin.com/in/samir-patel-assets",
    whatsappNumber: "+44 7701 112 224",
    phoneNumber: "+44 7701 112 224",
    workEmail: "samir@bridgewayres.com",
    personalEmail: "samir.patel@gmail.com",
  },
  {
    id: "nora-leasing",
    email: "nora@fourhops.local",
    name: "Nora Hayes",
    headline: "Head of Leasing @ Elmstone Living",
    linkedinUrl: "https://www.linkedin.com/in/nora-hayes-leasing",
    whatsappNumber: "+44 7701 112 225",
    phoneNumber: "+44 7701 112 225",
    workEmail: "nora@elmstoneliving.com",
    personalEmail: "nora.hayes@proton.me",
  },
  {
    id: "michael-facilities",
    email: "michael.facilities@fourhops.local",
    name: "Michael Stone",
    headline: "Regional Facilities Lead @ UrbanNest",
    linkedinUrl: "https://www.linkedin.com/in/michael-stone-facilities",
    whatsappNumber: "+44 7701 112 226",
    phoneNumber: "+44 7701 112 226",
    workEmail: "michael@urbannest.pm",
    personalEmail: "michael.stone@icloud.com",
  },
  {
    id: "olivia-turnarounds",
    email: "olivia@fourhops.local",
    name: "Olivia Grant",
    headline: "Operations Director @ Beacon Estates",
    linkedinUrl: "https://www.linkedin.com/in/olivia-grant-property",
    whatsappNumber: "+44 7701 112 227",
    phoneNumber: "+44 7701 112 227",
    workEmail: "olivia@beaconestates.com",
    personalEmail: "olivia.grant@gmail.com",
  },
  {
    id: "owner-investments",
    email: "gabriel@fourhops.local",
    name: "Gabriel Moss",
    headline: "Partner @ Cedar Peak Capital",
    linkedinUrl: "https://www.linkedin.com/in/gabriel-moss-investing",
    whatsappNumber: "+1 917 555 0131",
    phoneNumber: "+1 917 555 0131",
    workEmail: "gabriel@cedarpeakcap.com",
    personalEmail: "gabriel.moss@proton.me",
  },
  {
    id: "rachel-public",
    email: "rachel@fourhops.local",
    name: "Rachel Kim",
    headline: "Portfolio Manager @ Aster Global",
    linkedinUrl: "https://www.linkedin.com/in/rachel-kim-public-markets",
    whatsappNumber: "+1 917 555 0132",
    phoneNumber: "+1 917 555 0132",
    workEmail: "rachel@asterglobal.com",
    personalEmail: "rachel.kim@gmail.com",
  },
  {
    id: "devon-private",
    email: "devon@fourhops.local",
    name: "Devon Clarke",
    headline: "Principal @ Longview Ventures",
    linkedinUrl: "https://www.linkedin.com/in/devon-clarke-ventures",
    whatsappNumber: "+1 917 555 0133",
    phoneNumber: "+1 917 555 0133",
    workEmail: "devon@longviewvc.com",
    personalEmail: "devon.clarke@fastmail.com",
  },
  {
    id: "irina-credit",
    email: "irina@fourhops.local",
    name: "Irina Volkova",
    headline: "Head of Credit @ Meridian Yield",
    linkedinUrl: "https://www.linkedin.com/in/irina-volkova-credit",
    whatsappNumber: "+48 512 990 118",
    phoneNumber: "+48 512 990 118",
    workEmail: "irina@meridianyield.com",
    personalEmail: "irina.volkova@proton.me",
  },
  {
    id: "pablo-macro",
    email: "pablo@fourhops.local",
    name: "Pablo Ortega",
    headline: "Macro Strategist @ Horizon Field",
    linkedinUrl: "https://www.linkedin.com/in/pablo-ortega-macro",
    whatsappNumber: "+34 611 003 920",
    phoneNumber: "+34 611 003 920",
    workEmail: "pablo@horizonfield.com",
    personalEmail: "pablo.ortega@icloud.com",
  },
  {
    id: "owner-dogs",
    email: "maya.dogs@fourhops.local",
    name: "Maya Foster",
    headline: "Behavior Specialist @ Northside Canine",
    linkedinUrl: "https://www.linkedin.com/in/maya-foster-canine",
    whatsappNumber: "+44 7701 882 221",
    phoneNumber: "+44 7701 882 221",
    workEmail: "maya@northsidecanine.com",
    personalEmail: "maya.foster@gmail.com",
  },
  {
    id: "leo-puppy",
    email: "leo.puppy@fourhops.local",
    name: "Leo Bennett",
    headline: "Puppy Program Lead @ Good Start Dogs",
    linkedinUrl: "https://www.linkedin.com/in/leo-bennett-puppies",
    whatsappNumber: "+44 7701 882 222",
    phoneNumber: "+44 7701 882 222",
    workEmail: "leo@goodstartdogs.co.uk",
    personalEmail: "leo.bennett@fastmail.com",
  },
  {
    id: "tessa-workingdogs",
    email: "tessa@fourhops.local",
    name: "Tessa Novak",
    headline: "Working Dog Trainer @ IronLead K9",
    linkedinUrl: "https://www.linkedin.com/in/tessa-novak-workingdogs",
    whatsappNumber: "+44 7701 882 223",
    phoneNumber: "+44 7701 882 223",
    workEmail: "tessa@ironleadk9.com",
    personalEmail: "tessa.novak@proton.me",
  },
  {
    id: "harper-reactivity",
    email: "harper@fourhops.local",
    name: "Harper Lane",
    headline: "Reactivity Coach @ Steady Paws Studio",
    linkedinUrl: "https://www.linkedin.com/in/harper-lane-dogs",
    whatsappNumber: "+44 7701 882 224",
    phoneNumber: "+44 7701 882 224",
    workEmail: "harper@steadypawsstudio.com",
    personalEmail: "harper.lane@gmail.com",
  },
  {
    id: "omar-sportdogs",
    email: "omar.k9@fourhops.local",
    name: "Omar Haddad",
    headline: "Sport Dog Coach @ Apex K9 Club",
    linkedinUrl: "https://www.linkedin.com/in/omar-haddad-k9",
    whatsappNumber: "+44 7701 882 225",
    phoneNumber: "+44 7701 882 225",
    workEmail: "omar@apexk9club.com",
    personalEmail: "omar.haddad@icloud.com",
  },
  {
    id: "owner-music",
    email: "sienna@fourhops.local",
    name: "Sienna Vale",
    headline: "Producer @ Lantern Audio",
    linkedinUrl: "https://www.linkedin.com/in/sienna-vale-producer",
    whatsappNumber: "+44 7701 774 210",
    phoneNumber: "+44 7701 774 210",
    workEmail: "sienna@lanternaudio.com",
    personalEmail: "sienna.vale@gmail.com",
  },
  {
    id: "kai-mixing",
    email: "kai@fourhops.local",
    name: "Kai Mercer",
    headline: "Mix Engineer @ Greyline Studios",
    linkedinUrl: "https://www.linkedin.com/in/kai-mercer-mix",
    whatsappNumber: "+44 7701 774 211",
    phoneNumber: "+44 7701 774 211",
    workEmail: "kai@greylinestudios.com",
    personalEmail: "kai.mercer@proton.me",
  },
  {
    id: "elena-sync",
    email: "elena.sync@fourhops.local",
    name: "Elena Rossi",
    headline: "Sync Producer @ North Coast Music",
    linkedinUrl: "https://www.linkedin.com/in/elena-rossi-sync",
    whatsappNumber: "+39 347 881 8801",
    phoneNumber: "+39 347 881 8801",
    workEmail: "elena@northcoastmusic.com",
    personalEmail: "elena.rossi@icloud.com",
  },
  {
    id: "jon-drumprogramming",
    email: "jon@fourhops.local",
    name: "Jon Ellis",
    headline: "Production Lead @ Signal House",
    linkedinUrl: "https://www.linkedin.com/in/jon-ellis-production",
    whatsappNumber: "+44 7701 774 212",
    phoneNumber: "+44 7701 774 212",
    workEmail: "jon@signalhouseaudio.com",
    personalEmail: "jon.ellis@gmail.com",
  },
  {
    id: "ayumi-mastering",
    email: "ayumi@fourhops.local",
    name: "Ayumi Tanaka",
    headline: "Mastering Engineer @ Silver Room",
    linkedinUrl: "https://www.linkedin.com/in/ayumi-tanaka-mastering",
    whatsappNumber: "+81 90 4422 1188",
    phoneNumber: "+81 90 4422 1188",
    workEmail: "ayumi@silverroom.jp",
    personalEmail: "ayumi.tanaka@fastmail.com",
  },
];

const dummyUsers = Array.from({ length: 45 }, (_, index) => {
  const number = index + 1;
  const id = `waitlist-user-${String(number).padStart(2, "0")}`;
  const formatted = String(number).padStart(2, "0");
  const phone = `+48 600 ${String(100 + number).padStart(3, "0")} ${String(200 + number).padStart(3, "0")}`;

  return {
    id,
    email: `${id}@fourhops.local`,
    name: `Member ${formatted}`,
    headline: number % 3 === 0 ? "Founder @ DemoCo" : number % 3 === 1 ? "Operator @ DemoCo" : "Investor @ DemoCo",
    linkedinUrl: `https://www.linkedin.com/in/${id}`,
    whatsappNumber: phone,
    phoneNumber: phone,
    workEmail: `${id}@democo.io`,
    personalEmail: `${id}@gmail.com`,
  };
});

const allUsers = [...coreUsers, ...dummyUsers].map((user) => ({
  ...user,
  passwordHash: user.passwordHash ?? sharedPasswordHash,
  avatarUrl: sharedAvatarUrl,
}));

async function main() {
  await prisma.message.deleteMany();
  await prisma.conversation.deleteMany();
  await prisma.introduction.deleteMany();
  await prisma.reply.deleteMany();
  await prisma.request.deleteMany();
  await prisma.membership.deleteMany();
  await prisma.group.deleteMany();
  await prisma.user.deleteMany();

  await prisma.user.createMany({
    data: allUsers,
  });

  const now = new Date();
  const daysAgo = (days) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000);

  await prisma.group.createMany({
    data: [
      {
        id: "group-founders",
        name: "Founders in Warsaw",
        description: "Trusted peer group for founders getting help on hiring, growth, and fundraising.",
        whoFor: "Seed to Series B founders and operator-founders actively helping others solve real challenges in Europe.",
        whoNotFor: "Cold outreach, list collectors, and anyone looking for passive audience access.",
        valueProp: "Practical, high-context support from founders, operators, and investors who can act quickly.",
        ownerId: "temp-user",
        status: GroupStatus.active,
        memberCount: 12,
        publishedAt: now,
      },
      {
        id: "group-operators",
        name: "Operator Circle",
        description: "Senior operators sharing trusted connections and insight across product, growth, and hiring.",
        whoFor: "VP and director-level operators who can help each other with relevant connections and execution context.",
        whoNotFor: "Observers who consume requests without contributing useful replies.",
        valueProp: "Fast, trusted routing of operator asks to people who can credibly help.",
        ownerId: "maya-founder",
        status: GroupStatus.emerging,
        memberCount: 8,
        publishedAt: null,
      },
      {
        id: "group-health-ai",
        name: "Health AI Builders",
        description: "Private early-stage room shaping the bar for clinical AI support and signal quality.",
        whoFor: "A small number of health AI builders testing request quality before launch.",
        whoNotFor: "Broad marketplace demand or general networking asks.",
        valueProp: "Tightly screened support among people building in regulated AI workflows.",
        ownerId: "temp-user",
        status: GroupStatus.draft,
        memberCount: 3,
        publishedAt: null,
      },
      {
        id: "group-women-pharma",
        name: "Women Leaders in Pharma",
        description: "A private room for senior women in biotech and pharma making capital, clinical, regulatory, and leadership decisions under real time pressure.",
        whoFor: "Women leaders across biotech and pharma who can bring direct experience on clinical risk, fundraising, partnerships, and executive hiring.",
        whoNotFor: "Polite but empty commentary, vague asks, or anyone looking for access without contributing operating context.",
        valueProp: "Sharper decisions from women who have already made the tradeoffs you are facing now.",
        ownerId: "claire-clinical",
        status: GroupStatus.active,
        memberCount: 6,
        publishedAt: now,
      },
      {
        id: "group-digital-pharma",
        name: "Digital Pharma Executives",
        description: "A private group for senior leaders in pharma and biotech working through digital transformation, data strategy, AI adoption, and operating model decisions.",
        whoFor: "Senior digital, data, technology, regulatory, and operating leaders inside pharma and biotech making real decisions under regulatory and organizational constraints.",
        whoNotFor: "Beginner questions, trend-chasing, and anyone looking for generic innovation theatre instead of peer-level thinking.",
        valueProp: "Digital strategy, AI adoption, data infrastructure, and operating model decisions inside pharma.",
        ownerId: "anna-digital",
        status: GroupStatus.active,
        memberCount: 10,
        publishedAt: now,
      },
      {
        id: "group-property-management",
        name: "Property Management Operators",
        description: "A private room for senior property operators making decisions on occupancy, maintenance, team structure, and resident experience.",
        whoFor: "Leaders running multifamily, build-to-rent, and residential operations who can trade specific operating decisions, not generic landlord advice.",
        whoNotFor: "General real estate networking, passive investing questions, or people looking for templates without sharing real operating context.",
        valueProp: "Sharper operational decisions from people managing maintenance pressure, retention, and margin in real portfolios.",
        ownerId: "owner-property",
        status: GroupStatus.active,
        memberCount: 5,
        publishedAt: now,
      },
      {
        id: "group-investments",
        name: "Investment Decision Room",
        description: "A private room for investors and capital allocators pressure-testing theses, risk, and timing.",
        whoFor: "Public and private market investors who can contribute decision quality, not hot takes or market theatre.",
        whoNotFor: "Beginner portfolio questions, stock-picking hype, or anyone looking for signal without showing their own reasoning.",
        valueProp: "Clearer investment decisions from people used to sizing risk, defending downside, and changing their mind fast.",
        ownerId: "owner-investments",
        status: GroupStatus.active,
        memberCount: 5,
        publishedAt: now,
      },
      {
        id: "group-dog-training",
        name: "Dog Training Practitioners",
        description: "A private room for experienced trainers working through behavior cases, business decisions, and coaching tradeoffs.",
        whoFor: "Professional trainers who can bring real case experience on reactivity, puppy development, working dogs, and owner coaching.",
        whoNotFor: "Pet-owner questions, generic obedience tips, or anything that turns the room into consumer advice.",
        valueProp: "Better case decisions and sharper training judgment from people doing the work every week.",
        ownerId: "owner-dogs",
        status: GroupStatus.active,
        memberCount: 5,
        publishedAt: now,
      },
      {
        id: "group-music-production",
        name: "Music Production Room",
        description: "A private room for producers and engineers making creative and commercial decisions around records, mixes, and careers.",
        whoFor: "Working producers, mixers, and mastering engineers who can trade specifics on production choices, client management, and release strategy.",
        whoNotFor: "Beginner DAW questions, self-promo, or broad music industry chatter without decision pressure.",
        valueProp: "Sharper records and better studio decisions from people who know exactly what broke, what shipped, and what got paid.",
        ownerId: "owner-music",
        status: GroupStatus.active,
        memberCount: 5,
        publishedAt: now,
      },
    ],
  });

  const founderActiveIds = [
    "temp-user",
    "guest-user",
    "maya-founder",
    "leo-operator",
    "nina-investor",
    "alex-growth",
    "sara-product",
    "omar-fintech",
    "julia-ops",
    "eva-talent",
    "waitlist-user-01",
    "waitlist-user-02",
  ];

  const founderWaitlistIds = Array.from({ length: 35 }, (_, index) => `waitlist-user-${String(index + 3).padStart(2, "0")}`);
  const founderPendingIds = ["waitlist-user-38", "waitlist-user-39", "waitlist-user-40"];
  const founderInvitedIds = ["waitlist-user-41", "waitlist-user-42"];

  const operatorActiveIds = [
    "temp-user",
    "maya-founder",
    "leo-operator",
    "nina-investor",
    "ria-b2b",
    "tom-data",
    "waitlist-user-43",
    "waitlist-user-44",
    "waitlist-user-45",
  ];

  const pharmaActiveIds = [
    "claire-clinical",
    "priya-reg",
    "sofia-bd",
    "hannah-board",
    "lucia-medical",
    "elise-strategy",
  ];

  const pharmaWaitlistIds = [
    "nadia-portfolio",
    "marta-qa",
    "isabel-translational",
    "freya-finance",
    "julia-clinops",
    "amira-medaffairs",
    "helena-corpdev",
    "rebeca-ra",
    "camille-investor",
    "naomi-biometrics",
    "karin-pipeline",
    "aline-ceo",
    "signe-alliance",
  ];

  const digitalPharmaActiveIds = [
    "anna-digital",
    "marcus-data-pharma",
    "sophie-ai-pharma",
    "daniel-gxp",
    "isabella-ops-pharma",
    "jonas-platform",
    "meera-regops",
    "victor-commercial",
    "laura-enterprise-data",
    "peter-digital-brand",
  ];

  const propertyActiveIds = [
    "temp-user",
    "owner-property",
    "sam-asset",
    "nora-leasing",
    "michael-facilities",
    "olivia-turnarounds",
  ];
  const propertyWaitlistIds = ["waitlist-user-03", "waitlist-user-04", "waitlist-user-05", "waitlist-user-06"];

  const investmentsActiveIds = [
    "temp-user",
    "owner-investments",
    "rachel-public",
    "devon-private",
    "irina-credit",
    "pablo-macro",
  ];
  const investmentsWaitlistIds = ["waitlist-user-07", "waitlist-user-08", "waitlist-user-09", "waitlist-user-10"];

  const dogTrainingActiveIds = [
    "owner-dogs",
    "leo-puppy",
    "tessa-workingdogs",
    "harper-reactivity",
    "omar-sportdogs",
  ];
  const dogTrainingWaitlistIds = ["waitlist-user-11", "waitlist-user-12", "waitlist-user-13", "waitlist-user-14"];

  const musicActiveIds = [
    "owner-music",
    "kai-mixing",
    "elena-sync",
    "jon-drumprogramming",
    "ayumi-mastering",
  ];
  const musicWaitlistIds = ["waitlist-user-15", "waitlist-user-16", "waitlist-user-17", "waitlist-user-18"];

  const membershipRows = [
    ...founderActiveIds.map((userId, index) => ({
      id: `m-founders-active-${userId}`,
      userId,
      groupId: "group-founders",
      role: userId === "temp-user" ? MembershipRole.owner : MembershipRole.member,
      status: MembershipStatus.active,
      createdAt: daysAgo(60 - index),
    })),
    ...founderWaitlistIds.map((userId, index) => ({
      id: `m-founders-waitlist-${userId}`,
      userId,
      groupId: "group-founders",
      role: MembershipRole.member,
      status: MembershipStatus.waitlist,
      createdAt: daysAgo(Math.max(2, 30 - index)),
    })),
    ...founderPendingIds.map((userId, index) => ({
      id: `m-founders-pending-${userId}`,
      userId,
      groupId: "group-founders",
      role: MembershipRole.member,
      status: MembershipStatus.pending,
      recommendedByUserId: index === 0 ? "julia-ops" : null,
      fitWhy:
        index === 0
          ? "I run product and hiring for a 70-person B2B SaaS team in Warsaw and the founder-to-exec transition topics in this room are directly relevant to the decisions I am making now."
          : index === 1
            ? "I lead finance at a Series A fintech and want a sharper room for operator-level decisions around hiring, fundraising, and org design."
            : "I am scaling operations across two markets and need a room where people respond from lived experience rather than generic startup advice.",
      contributionWhy:
        index === 0
          ? "I can contribute clear context on VP Product hiring, product org resets, and what breaks when founder-led roadmap decisions last too long."
          : index === 1
            ? "I can help with finance leadership hiring, board prep, and capital planning tradeoffs from inside a fast-moving fintech environment."
            : "I can contribute operator perspective on execution discipline, hiring signal, and where scale starts to create real internal drag.",
      relevantContext:
        index === 0
          ? "Warsaw based, product-led SaaS, recently crossed 60 people."
          : index === 1
            ? "Berlin fintech, Series A, leading finance and strategic planning."
            : "CEE operator, multi-market team, managing scale-up execution issues.",
      createdAt: daysAgo(3 - Math.min(index, 2)),
    })),
    ...founderInvitedIds.map((userId, index) => ({
      id: `m-founders-invited-${userId}`,
      userId,
      groupId: "group-founders",
      role: MembershipRole.invitee,
      status: MembershipStatus.invited,
      createdAt: daysAgo(1 + index),
    })),
    ...operatorActiveIds.map((userId, index) => ({
      id: `m-operators-active-${userId}`,
      userId,
      groupId: "group-operators",
      role: userId === "maya-founder" ? MembershipRole.owner : MembershipRole.member,
      status: MembershipStatus.active,
      createdAt: daysAgo(35 - index),
    })),
    ...pharmaActiveIds.map((userId, index) => ({
      id: `m-pharma-active-${userId}`,
      userId,
      groupId: "group-women-pharma",
      role: userId === "claire-clinical" ? MembershipRole.owner : MembershipRole.member,
      status: MembershipStatus.active,
      createdAt: daysAgo(40 - index),
    })),
    ...pharmaWaitlistIds.map((userId, index) => ({
      id: `m-pharma-waitlist-${userId}`,
      userId,
      groupId: "group-women-pharma",
      role: MembershipRole.member,
      status: MembershipStatus.waitlist,
      createdAt: daysAgo(Math.max(2, 18 - index)),
    })),
    ...digitalPharmaActiveIds.map((userId, index) => ({
      id: `m-digital-pharma-active-${userId}`,
      userId,
      groupId: "group-digital-pharma",
      role: userId === "anna-digital" ? MembershipRole.owner : MembershipRole.member,
      status: MembershipStatus.active,
      createdAt: daysAgo(55 - index),
    })),
    ...propertyActiveIds.map((userId, index) => ({
      id: `m-property-active-${userId}`,
      userId,
      groupId: "group-property-management",
      role: userId === "owner-property" ? MembershipRole.owner : MembershipRole.member,
      status: MembershipStatus.active,
      createdAt: daysAgo(34 - index),
    })),
    ...propertyWaitlistIds.map((userId, index) => ({
      id: `m-property-waitlist-${userId}`,
      userId,
      groupId: "group-property-management",
      role: MembershipRole.member,
      status: MembershipStatus.waitlist,
      createdAt: daysAgo(8 - index),
    })),
    ...investmentsActiveIds.map((userId, index) => ({
      id: `m-investments-active-${userId}`,
      userId,
      groupId: "group-investments",
      role: userId === "owner-investments" ? MembershipRole.owner : MembershipRole.member,
      status: MembershipStatus.active,
      createdAt: daysAgo(30 - index),
    })),
    ...investmentsWaitlistIds.map((userId, index) => ({
      id: `m-investments-waitlist-${userId}`,
      userId,
      groupId: "group-investments",
      role: MembershipRole.member,
      status: MembershipStatus.waitlist,
      createdAt: daysAgo(9 - index),
    })),
    ...dogTrainingActiveIds.map((userId, index) => ({
      id: `m-dog-training-active-${userId}`,
      userId,
      groupId: "group-dog-training",
      role: userId === "owner-dogs" ? MembershipRole.owner : MembershipRole.member,
      status: MembershipStatus.active,
      createdAt: daysAgo(28 - index),
    })),
    ...dogTrainingWaitlistIds.map((userId, index) => ({
      id: `m-dog-training-waitlist-${userId}`,
      userId,
      groupId: "group-dog-training",
      role: MembershipRole.member,
      status: MembershipStatus.waitlist,
      createdAt: daysAgo(7 - index),
    })),
    ...musicActiveIds.map((userId, index) => ({
      id: `m-music-active-${userId}`,
      userId,
      groupId: "group-music-production",
      role: userId === "owner-music" ? MembershipRole.owner : MembershipRole.member,
      status: MembershipStatus.active,
      createdAt: daysAgo(26 - index),
    })),
    ...musicWaitlistIds.map((userId, index) => ({
      id: `m-music-waitlist-${userId}`,
      userId,
      groupId: "group-music-production",
      role: MembershipRole.member,
      status: MembershipStatus.waitlist,
      createdAt: daysAgo(6 - index),
    })),
    {
      id: "m-owner-health",
      userId: "temp-user",
      groupId: "group-health-ai",
      role: MembershipRole.owner,
      status: MembershipStatus.active,
      createdAt: daysAgo(14),
    },
    {
      id: "m-zoe-health",
      userId: "zoe-health",
      groupId: "group-health-ai",
      role: MembershipRole.member,
      status: MembershipStatus.active,
      createdAt: daysAgo(11),
    },
    {
      id: "m-liam-health",
      userId: "liam-ai",
      groupId: "group-health-ai",
      role: MembershipRole.member,
      status: MembershipStatus.active,
      createdAt: daysAgo(9),
    },
  ];

  await prisma.membership.createMany({
    data: membershipRows,
  });

  await prisma.membershipVote.createMany({
    data: [
      {
        id: "vote-founders-pending-1",
        membershipId: `m-founders-pending-${founderPendingIds[0]}`,
        voterId: "temp-user",
        createdAt: daysAgo(1),
      },
      {
        id: "vote-founders-pending-2",
        membershipId: `m-founders-pending-${founderPendingIds[0]}`,
        voterId: "maya-founder",
        createdAt: daysAgo(1),
      },
      {
        id: "vote-founders-pending-3",
        membershipId: `m-founders-pending-${founderPendingIds[1]}`,
        voterId: "julia-ops",
        createdAt: daysAgo(1),
      },
    ],
  });

  await prisma.request.createMany({
    data: [
      {
        id: "request-guest-main",
        title: "Fintech CFO search (Berlin)",
        content: "Need a warm intro to a fintech CFO in Berlin who has scaled a 50-person finance team.",
        kind: DiscussionKind.request,
        creatorId: "guest-user",
        groupId: "group-founders",
        status: RequestStatus.open,
        pinned: true,
      },
      {
        id: "request-alex-main",
        title: "Growth leaders in Paris",
        content: "Looking for an operator who can connect me to B2B growth leaders in Paris.",
        kind: DiscussionKind.question,
        creatorId: "alex-growth",
        groupId: "group-founders",
        status: RequestStatus.closed,
        outcome: "We stopped leading with a conservative risk disclaimer and instead anchored the deck around one credible downside case, our mitigation plan, and the trigger points investors should watch. That made the story feel disciplined rather than hesitant, and it kept both specialist and crossover funds engaged.",
        outcomeType: OutcomeType.direction_clarified,
        helpfulSource: "Claire Morgan, Elise Laurent, Priya Shah, and Sofia Alvarez",
        resolvedAt: daysAgo(1),
      },
      {
        id: "request-sara-hiring",
        title: "First VP Product hire in Warsaw",
        content: "Need perspective on first VP Product hires for a Series B fintech team in Warsaw.",
        kind: DiscussionKind.insight,
        creatorId: "sara-product",
        groupId: "group-founders",
        status: RequestStatus.open,
      },
      {
        id: "request-nina-operators",
        title: "AI infra founders entering Europe",
        content: "Need an introduction to AI infra founders expanding into Europe this quarter.",
        kind: DiscussionKind.update,
        creatorId: "nina-investor",
        groupId: "group-operators",
        status: RequestStatus.closed,
        outcome: "Perspective shared",
      },
      {
        id: "request-pharma-cmo",
        title: "First Chief Medical Officer hire at Series B — what worked for you?",
        content: "We're starting to formalize clinical strategy and are debating when to bring in a full-time CMO vs continuing with advisors.\n\nContext:\n• Series B biotech, ~45 people\n• Early clinical signals but not yet in Phase II\n• Strong external advisors already in place\n\nWhere I'd value perspective:\n• When did a full-time CMO become necessary for you?\n• What profile actually worked (big pharma vs startup-heavy)?\n• Anything you got wrong the first time?\n\nTrying to avoid hiring too early or bringing in the wrong type of operator.",
        kind: DiscussionKind.request,
        creatorId: "claire-clinical",
        groupId: "group-women-pharma",
        status: RequestStatus.open,
        pinned: true,
      },
      {
        id: "request-pharma-seriesc",
        title: "Positioning clinical risk in Series C fundraising — what actually kept investors in the process?",
        content: "We're about to open a Series C and the hardest part of the narrative is clinical risk.\n\nLast time we leaned conservative, the story lost momentum fast. Now some investors want downside spelled out clearly, while others react as if naming risk means we do not believe our own plan.\n\nContext:\n• Late preclinical moving into Phase I readiness\n• Scientific case is strong, but timing still has real variance\n• Board wants a message we can repeat without sounding either naive or defensive\n\nWhat I need help with:\n• What did you say explicitly in partner meetings that kept credibility high?\n• What language immediately killed energy?\n• Did you frame risk around mitigation, sequencing, or expected downside first?\n\nTrying to avoid the two bad outcomes: sounding promotional to specialists or fragile to generalists.",
        kind: DiscussionKind.update,
        creatorId: "hannah-board",
        groupId: "group-women-pharma",
        status: RequestStatus.open,
      },
      {
        id: "request-pharma-bd",
        title: "Seeing longer decision cycles from big pharma partners this year",
        content: "We've noticed a clear shift in BD timelines over the past 6–9 months.\n\nProcesses that used to take ~3 months are now stretching to 6+ with more internal stakeholders involved.\n\nNot sure if this is:\n• macro-driven caution\n• internal budget pressure\n• or just more competition for attention\n\nCurious if others are seeing the same, especially in EU vs US teams.\n\nFeels like it's starting to impact how we plan partnerships.",
        kind: DiscussionKind.insight,
        creatorId: "sofia-bd",
        groupId: "group-women-pharma",
        status: RequestStatus.open,
      },
      {
        id: "request-pharma-us",
        title: "Would you expand into the US before Phase II?",
        content: "We're debating whether to establish a US presence now or wait until we have stronger clinical validation.\n\nContext:\n• EU-based team\n• Early traction with US investors and advisors\n• Limited operational bandwidth\n\nTradeoff seems to be:\n• earlier access to capital and partnerships\nvs\n• distraction from core execution\n\nWould love to hear how others thought about timing here.",
        kind: DiscussionKind.question,
        creatorId: "priya-reg",
        groupId: "group-women-pharma",
        status: RequestStatus.open,
      },
      {
        id: "request-pharma-regulatory",
        title: "Hiring regulatory leadership — internal vs external credibility",
        content: "We're looking for someone to lead regulatory and are torn between:\n\n• someone with deep FDA experience from big pharma\n• vs someone more startup-native who can operate with less structure\n\nContext:\n• small but growing team (~30)\n• entering more formal regulatory processes for the first time\n\nConcern is:\n• big pharma profile might struggle in ambiguity\n• startup profile might lack credibility externally\n\nCurious what has actually worked in practice for others.",
        kind: DiscussionKind.request,
        creatorId: "lucia-medical",
        groupId: "group-women-pharma",
        status: RequestStatus.open,
      },
      {
        id: "request-pharma-board",
        title: "How involved are your boards in clinical strategy decisions?",
        content: "We're seeing increasing board involvement in decisions that used to sit fully with the exec team.\n\nContext:\n• mix of VC + strategic investors\n• strong opinions around trial design and timelines\n\nTrying to find the right balance between:\n• leveraging their experience\n• vs slowing down decision-making\n\nWould be useful to hear how others are managing this.",
        kind: DiscussionKind.update,
        creatorId: "elise-strategy",
        groupId: "group-women-pharma",
        status: RequestStatus.open,
      },
      {
        id: "request-dpe-ai-value",
        title: "Where is AI actually creating measurable value inside pharma orgs right now?",
        content: "We're reviewing the next 12 months of digital investment and trying to separate real operating value from slideware.\n\nContext:\n- commercial, medical, clinical, and regulatory teams all have different AI asks\n- internal productivity gains are easier to prove than external workflow changes\n- compliance and validation overhead are slowing rollout in the highest-value regulated areas\n\nWhat I'm trying to understand:\n- where are you seeing measurable value today\n- which use cases survived past the pilot phase\n- where did cost and governance outweigh the upside",
        kind: DiscussionKind.question,
        creatorId: "anna-digital",
        groupId: "group-digital-pharma",
        status: RequestStatus.open,
        pinned: true,
        createdAt: daysAgo(6),
      },
      {
        id: "request-dpe-data-teams",
        title: "Centralized vs embedded data teams - what actually works at scale?",
        content: "We are reworking the data operating model across R&D, regulatory, and commercial.\n\nContext:\n- central team has improved standards but slowed decision speed\n- embedded analysts increase relevance but create duplication quickly\n- leaders are asking for one answer, but the tradeoff seems more structural than organizational\n\nWhat has worked in practice:\n- where do you centralize\n- what stays embedded\n- what broke when you pushed too far in either direction",
        kind: DiscussionKind.update,
        creatorId: "marcus-data-pharma",
        groupId: "group-digital-pharma",
        status: RequestStatus.open,
        pinned: true,
        createdAt: daysAgo(5),
      },
      {
        id: "request-dpe-head-ai",
        title: "Hiring a Head of AI in pharma - academic depth or operator profile?",
        content: "We're opening a senior AI role and the brief is drifting between research credibility and operating execution.\n\nContext:\n- team is strong technically but weak on cross-functional adoption\n- board wants visible AI leadership quickly\n- internal teams need someone who can ship in a regulated environment, not just speak at conferences\n\nWhere I'm unsure:\n- how much scientific depth matters at this level\n- whether a pharma-native operator outperforms a stronger external AI profile\n- what failure mode you saw first when the profile was wrong",
        kind: DiscussionKind.request,
        creatorId: "sophie-ai-pharma",
        groupId: "group-digital-pharma",
        status: RequestStatus.open,
        createdAt: daysAgo(4),
      },
      {
        id: "request-dpe-explainability",
        title: "How are you handling AI explainability requirements in regulated workflows?",
        content: "We're getting closer to deploying AI into workflows that feed regulated decisions, and explainability is becoming the blocking issue.\n\nContext:\n- quality and regulatory teams want traceability before scale\n- product teams are arguing for narrower deployments with more human review\n- vendors all claim compliance readiness but very little holds up in validation detail\n\nWould value practical input on:\n- what standard you are actually holding teams to\n- how much explainability is enough in real approvals\n- where you drew a line and said no",
        kind: DiscussionKind.question,
        creatorId: "daniel-gxp",
        groupId: "group-digital-pharma",
        status: RequestStatus.open,
        createdAt: daysAgo(3),
      },
      {
        id: "request-dpe-build-buy",
        title: "Build vs buy for clinical data platforms - where did you draw the line?",
        content: "We're in the usual trap of wanting flexibility without inheriting a long-term platform problem.\n\nContext:\n- off-the-shelf platforms solve 70 percent of what we need\n- custom workflows around trial operations and data review are where the pain starts\n- engineering is confident we can build the missing layer, but not the whole stack responsibly\n\nTrying to learn:\n- where you stopped building\n- what you regretted outsourcing\n- what became technical debt faster than expected",
        kind: DiscussionKind.question,
        creatorId: "jonas-platform",
        groupId: "group-digital-pharma",
        status: RequestStatus.open,
        createdAt: daysAgo(5),
      },
      {
        id: "request-dpe-change-management",
        title: "Why do most digital transformation efforts stall after year 2?",
        content: "We've seen strong momentum in year one and then a steady slide into governance theatre and competing priorities.\n\nContext:\n- sponsors change\n- business teams stop seeing near-term wins\n- capability teams end up defending platforms instead of solving problems\n\nI'm looking for real pattern recognition here:\n- what actually caused the stall in your case\n- what reset momentum if anything did\n- what you would cut earlier next time",
        kind: DiscussionKind.insight,
        creatorId: "isabella-ops-pharma",
        groupId: "group-digital-pharma",
        status: RequestStatus.open,
        createdAt: daysAgo(7),
      },
      {
        id: "request-dpe-board-roi",
        title: "How do you explain digital ROI to non-technical boards?",
        content: "Our board is supportive in principle but still evaluates digital spending like a sequence of standalone tools.\n\nContext:\n- value often comes from operating leverage, risk reduction, and cycle time improvements rather than a clean revenue line\n- technical debt and data quality work feel essential internally but abstract in board conversation\n- too much detail loses the room quickly\n\nHow are you framing this in a way that creates confidence without over-promising?",
        kind: DiscussionKind.update,
        creatorId: "victor-commercial",
        groupId: "group-digital-pharma",
        status: RequestStatus.open,
        createdAt: daysAgo(2),
      },
      {
        id: "request-dpe-failure-share",
        title: "What failed in your last digital transformation effort - and why?",
        content: "I'm less interested in polished retrospectives and more in the call you got wrong.\n\nContext:\n- we're about to restructure the digital portfolio and I want the team to learn from actual misses, not slogans\n- most failures here look reasonable in Q1 and obvious only much later\n- the pattern I care about is where leadership misread incentives, sequencing, or ownership\n\nIf you have one example that still changed how you operate, I'd value hearing it plainly.",
        kind: DiscussionKind.insight,
        creatorId: "laura-enterprise-data",
        groupId: "group-digital-pharma",
        status: RequestStatus.open,
        createdAt: daysAgo(1),
      },
      {
        id: "request-dpe-vendor-governance",
        title: "Vendor sprawl across digital initiatives - when did you force a reset?",
        content: "We now have overlapping AI, data integration, orchestration, and workflow vendors across the same portfolio.\n\nContext:\n- every function can defend its own stack locally\n- integration effort is quietly compounding quarter to quarter\n- no one wants to trigger a consolidation effort because it will slow current delivery\n\nTrying to decide whether to let this run for another year or take the pain now.",
        kind: DiscussionKind.question,
        creatorId: "meera-regops",
        groupId: "group-digital-pharma",
        status: RequestStatus.open,
        createdAt: daysAgo(1),
      },
      {
        id: "request-property-occupancy",
        title: "Concessions are back — when do you hold rate and accept slower leasing?",
        content: "Occupancy is still fine on paper, but leasing velocity has slowed and the team wants to push concessions harder.\n\nContext:\n- mid-market multifamily across two cities\n- renewals are holding better than new lets\n- operating costs are still climbing, so rate integrity matters more than last year\n\nWhat I need help with:\n- when did you hold rate and win anyway\n- when did you cave too late and hurt velocity\n- what metric actually told you the market had turned",
        kind: DiscussionKind.question,
        creatorId: "owner-property",
        groupId: "group-property-management",
        status: RequestStatus.open,
        pinned: true,
        createdAt: daysAgo(3),
      },
      {
        id: "request-property-maintenance",
        title: "In-house maintenance vs outsourced overflow — where did your service level actually improve?",
        content: "We keep bouncing between adding more in-house techs and outsourcing overflow work when backlogs spike.\n\nContext:\n- portfolio has grown faster than the ops team\n- outsourced coverage looks cheaper until callbacks show up\n- in-house hiring is slower than residents are willing to wait\n\nTrying to decide what should stay owned versus flexed.",
        kind: DiscussionKind.request,
        creatorId: "sam-asset",
        groupId: "group-property-management",
        status: RequestStatus.open,
        createdAt: daysAgo(2),
      },
      {
        id: "request-property-onsite",
        title: "Do your best onsite managers get promoted too early?",
        content: "We keep moving strong onsite operators into regional roles and then wondering why site execution drops.\n\nContext:\n- promotion path is the main retention lever we have\n- regional roles look like the reward, but not everyone should leave the building level\n- we may be stripping the portfolio of our strongest local operators too fast\n\nWould value plain experience on what you changed here.",
        kind: DiscussionKind.insight,
        creatorId: "olivia-turnarounds",
        groupId: "group-property-management",
        status: RequestStatus.open,
        createdAt: daysAgo(1),
      },
      {
        id: "request-investments-sizing",
        title: "When did you deliberately under-size a position even though conviction was high?",
        content: "We have a name we like a lot, but the path is messy and I do not trust the timing.\n\nContext:\n- thesis is intact\n- downside is survivable, but mark-to-market pain could be real for 2–3 quarters\n- team is split between buying conviction and waiting for a cleaner setup\n\nLooking for cases where you were right on the business but wrong on the size.",
        kind: DiscussionKind.question,
        creatorId: "owner-investments",
        groupId: "group-investments",
        status: RequestStatus.open,
        pinned: true,
        createdAt: daysAgo(4),
      },
      {
        id: "request-investments-committee",
        title: "What actually changes an investment committee's mind late in the process?",
        content: "We keep getting to the final conversation with good work done and then watching committee energy fade for reasons nobody says directly.\n\nContext:\n- public/private crossover lens\n- strong upside, but non-consensus angle\n- lead sponsor is bought in, committee is still lukewarm\n\nWhat moved the room for you when the work was already done?",
        kind: DiscussionKind.update,
        creatorId: "rachel-public",
        groupId: "group-investments",
        status: RequestStatus.open,
        createdAt: daysAgo(2),
      },
      {
        id: "request-investments-risk",
        title: "What risk did you underwrite correctly that everyone else thought was fatal?",
        content: "I am less interested in the winner and more in the risk that looked obvious to the market and was not.\n\nContext:\n- our best returns lately have come from being right about recoverability, not growth\n- internal process still tends to over-penalize ugly near-term setups\n- I want better language for distinguishing temporary damage from permanent impairment",
        kind: DiscussionKind.insight,
        creatorId: "pablo-macro",
        groupId: "group-investments",
        status: RequestStatus.open,
        createdAt: daysAgo(1),
      },
      {
        id: "request-dogs-reactivity",
        title: "What made your reactive-dog cases move faster — cleaner mechanics or calmer owners?",
        content: "We keep saying the dog is the case, but owner handling is usually the thing stalling progress.\n\nContext:\n- medium to severe leash reactivity\n- owners are committed but inconsistent under stress\n- dogs improve in session and then regress at home\n\nTrying to get sharper about what to fix first instead of repeating the same plan louder.",
        kind: DiscussionKind.question,
        creatorId: "owner-dogs",
        groupId: "group-dog-training",
        status: RequestStatus.open,
        pinned: true,
        createdAt: daysAgo(3),
      },
      {
        id: "request-dogs-puppy",
        title: "Where do you draw the line between normal puppy chaos and future behavior debt?",
        content: "Owners are showing up earlier, but a lot of what they want fixed is just development.\n\nContext:\n- high-energy working mixes and larger breeds\n- social media has people pathologizing normal puppy behavior\n- the real risk is missing the cases where early structure actually matters\n\nWhat signs make you intervene harder sooner?",
        kind: DiscussionKind.request,
        creatorId: "leo-puppy",
        groupId: "group-dog-training",
        status: RequestStatus.open,
        createdAt: daysAgo(2),
      },
      {
        id: "request-dogs-sport",
        title: "What training advice do you stop giving because owners hear it but do not execute it?",
        content: "There are a few pieces of technically correct advice that sound smart and fail in the real world because clients do not implement them well.\n\nI am interested in what you have simplified or dropped entirely because compliance matters more than purity.",
        kind: DiscussionKind.insight,
        creatorId: "omar-sportdogs",
        groupId: "group-dog-training",
        status: RequestStatus.open,
        createdAt: daysAgo(1),
      },
      {
        id: "request-music-vocals",
        title: "How much vocal tuning is too much before the record loses urgency?",
        content: "We are finishing a pop record and the roughs had more life than the polished edits.\n\nContext:\n- artist wants clean, label wants competitive, team misses the urgency of the original takes\n- comping is done, tuning choices are what changed the feel\n- nobody wants to be the person who leaves obvious flaws in by mistake\n\nLooking for the line where cleanup starts costing emotion.",
        kind: DiscussionKind.question,
        creatorId: "owner-music",
        groupId: "group-music-production",
        status: RequestStatus.open,
        pinned: true,
        createdAt: daysAgo(4),
      },
      {
        id: "request-music-mix-revisions",
        title: "When do you stop doing free revisions and reset the client relationship?",
        content: "A project that should have taken three revision rounds is now on round eight and the notes are getting worse, not better.\n\nContext:\n- independent artist with management involved late\n- budget was fine at the start, not now\n- I want to preserve the relationship without training the client that limitless revisions are normal",
        kind: DiscussionKind.update,
        creatorId: "kai-mixing",
        groupId: "group-music-production",
        status: RequestStatus.open,
        createdAt: daysAgo(2),
      },
      {
        id: "request-music-sync",
        title: "What makes a track sync-ready versus just well-produced?",
        content: "We have records that sound expensive but still do not place.\n\nContext:\n- mixes are strong, but editors say they are hard to cut around\n- intros are too long more often than we admit\n- artists hate when we make arrangement choices for sync practicality\n\nWhat changes actually improved placements for you?",
        kind: DiscussionKind.insight,
        creatorId: "elena-sync",
        groupId: "group-music-production",
        status: RequestStatus.open,
        createdAt: daysAgo(1),
      },
    ],
  });

  await prisma.reply.createMany({
    data: [
      {
        id: "reply-guest-1",
        requestId: "request-guest-main",
        senderId: "temp-user",
        body: "We ran into this exact issue last quarter. Nina is probably the best first call here and she has fresh context on Berlin finance operators.",
        signal: "Useful perspective",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-guest-2",
        requestId: "request-guest-main",
        senderId: "julia-ops",
        body: "I'd actually push back a bit on going straight to CFO at 50 people. We had more luck with former VP Finance profiles who'd already scaled from 20 to 80 people.",
        signal: "Marked as helpful",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-alex-1",
        requestId: "request-alex-main",
        senderId: "leo-operator",
        body: "Happy to make a couple of introductions here. Two operator circles in Paris have been unusually responsive on B2B growth lately.",
        signal: "Led to an introduction",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-sara-1",
        requestId: "request-sara-hiring",
        senderId: "maya-founder",
        body: "We waited too long on this hire at Series B and felt it pretty quickly. Happy to share what changed once product and design started drifting, if that's useful.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-pharma-cmo-1",
        requestId: "request-pharma-cmo",
        senderId: "lucia-medical",
        body: "We hired a full-time CMO slightly too early, around 40 people, and it created more structure than we needed at that stage. In hindsight, the inflection point was less about team size and more about when external stakeholders started expecting consistency in how we communicated clinical strategy. If your advisors are still actively engaged and aligned, I'd probably stretch that model a bit longer.",
        signal: "Useful perspective",
        createdAt: daysAgo(3),
      },
      {
        id: "reply-pharma-cmo-2",
        requestId: "request-pharma-cmo",
        senderId: "hannah-board",
        body: "I'd actually argue the opposite — the earlier CMO hire gave us a huge advantage in shaping trial design and building credibility with partners. The key was finding someone who had big pharma experience but was comfortable operating without full infrastructure. The wrong profile is the bigger risk than the timing.",
        signal: "Marked as helpful",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-pharma-cmo-3",
        requestId: "request-pharma-cmo",
        senderId: "sofia-bd",
        body: "I can suggest someone who moved from a mid-sized biotech into a similar stage company and handled this transition well. Happy to share context if useful — she's currently advising a couple of teams in a similar position.",
        signal: "Led to an introduction",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-pharma-seriesc-1",
        requestId: "request-pharma-seriesc",
        senderId: "claire-clinical",
        body: "We tried softening the risk language to keep the deck optimistic and it backfired. The serious funds immediately assumed we were hiding something. What worked was one explicit downside case, one mitigation plan, and one sentence on what would trigger a timeline reset.",
        signal: "Useful perspective",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-pharma-seriesc-2",
        requestId: "request-pharma-seriesc",
        senderId: "elise-strategy",
        body: "We made the mistake of turning the whole narrative into risk management. Investors left the meeting understanding the downside in detail and the upside only vaguely. The fix was to keep the company-building story front and center, then show that management had already thought three moves ahead on risk.",
        signal: "Marked as helpful",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-pharma-seriesc-3",
        requestId: "request-pharma-seriesc",
        senderId: "priya-reg",
        body: "Do not give specialists and crossover funds the same answer here. Specialists wanted our actual risk register. Generalists wanted to know whether the team looked honest and in control. We used the same facts, but not the same framing, and the meetings got materially better.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-pharma-seriesc-4",
        requestId: "request-pharma-seriesc",
        senderId: "sofia-bd",
        body: "One thing I would not do again: opening with probability language. The moment we said 'high likelihood' the room started debating assumptions instead of the program. We switched to milestone language with explicit fail conditions and the conversation stayed commercial instead of philosophical.",
        signal: "Led to a conversation",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-pharma-bd-1",
        requestId: "request-pharma-bd",
        senderId: "hannah-board",
        body: "We're seeing the same, especially with larger pharma. There are just more internal checkpoints now, and decisions seem to require broader alignment than before. It's definitely impacting how we think about partnership timing.",
        signal: "Useful perspective",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-pharma-bd-2",
        requestId: "request-pharma-bd",
        senderId: "elise-strategy",
        body: "Agree on longer timelines, but we've had better luck when we anchor discussions around very specific collaboration scopes early. The more defined the starting point, the easier it seems to be for internal teams to move things forward.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-pharma-bd-3",
        requestId: "request-pharma-bd",
        senderId: "lucia-medical",
        body: "We've actually seen the opposite with smaller biotech partners — things are moving faster than last year. Feels like a bifurcation between large and mid-sized players.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-pharma-us-1",
        requestId: "request-pharma-us",
        senderId: "claire-clinical",
        body: "We expanded into the US too early and underestimated the operational overhead. It didn't materially accelerate fundraising for us, but it did create distraction. If you already have strong US investor access, I'd delay until there's a clearer need.",
        signal: "Useful perspective",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-pharma-us-2",
        requestId: "request-pharma-us",
        senderId: "sofia-bd",
        body: "We did the opposite — set up a small US presence early — and it significantly improved our access to both investors and partners. The key was keeping it extremely lean, one or two people, and very focused on relationship-building.",
        signal: "Marked as helpful",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-pharma-us-3",
        requestId: "request-pharma-us",
        senderId: "hannah-board",
        body: "One middle ground we've seen work well: no formal expansion, but consistent presence through travel and advisors. Gives you access without committing fully too early.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-pharma-regulatory-1",
        requestId: "request-pharma-regulatory",
        senderId: "priya-reg",
        body: "We went with a big pharma profile and struggled initially. They brought credibility, but needed more structure than we could provide at the time. Once we clarified scope and expectations, it improved — but it took time.",
        signal: "Useful perspective",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-pharma-regulatory-2",
        requestId: "request-pharma-regulatory",
        senderId: "claire-clinical",
        body: "We prioritized adaptability over pedigree and it worked well for us. The person had less direct FDA experience but was very effective in navigating ambiguity and building the function from scratch. We supplemented gaps with external advisors.",
        signal: "Marked as helpful",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-pharma-regulatory-3",
        requestId: "request-pharma-regulatory",
        senderId: "elise-strategy",
        body: "I think this is less about background and more about mindset. We've seen big pharma profiles work really well when they actively choose startup environments and have done it before. The first-time transition is where things tend to break.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-pharma-board-1",
        requestId: "request-pharma-board",
        senderId: "hannah-board",
        body: "We saw a similar shift as we got closer to clinical milestones. The most helpful change we made was clearly defining which decisions were inform vs input vs decide. It reduced a lot of friction.",
        signal: "Useful perspective",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-pharma-board-2",
        requestId: "request-pharma-board",
        senderId: "claire-clinical",
        body: "I'd be careful not to let this drift too far. We leaned too heavily on the board early on and it slowed us down significantly. Their input is valuable, but the operating team still needs to own decisions.",
        signal: "Marked as helpful",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-pharma-board-3",
        requestId: "request-pharma-board",
        senderId: "lucia-medical",
        body: "We've found it helpful to bring the board in earlier on framing, but keep final decisions within the exec team. That way you get the benefit of perspective without losing speed.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-dpe-ai-value-1",
        requestId: "request-dpe-ai-value",
        senderId: "marcus-data-pharma",
        body: "We are seeing measurable value in medical content operations and signal detection support, not in the flashy external use cases everyone wants to lead with. The highest-return work has been narrower, internal, and tied to cycle time rather than headline innovation.",
        signal: "Marked as helpful",
        createdAt: daysAgo(4),
      },
      {
        id: "reply-dpe-ai-value-2",
        requestId: "request-dpe-ai-value",
        senderId: "daniel-gxp",
        body: "I would push back on broad clinical use cases right now unless your validation discipline is already mature. We spent more time proving controls than we saved in the workflow, which made the economics look far worse than the pilot case did.",
        signal: "Useful perspective",
        createdAt: daysAgo(3),
      },
      {
        id: "reply-dpe-ai-value-3",
        requestId: "request-dpe-ai-value",
        senderId: "peter-digital-brand",
        body: "Commercial content ops has been the clearest win for us because adoption friction was low and the teams felt value immediately. The lesson was not AI first, but governance light enough that the business would actually use it.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-dpe-data-teams-1",
        requestId: "request-dpe-data-teams",
        senderId: "laura-enterprise-data",
        body: "We tried centralizing data early and it slowed everything down. The teams lost ownership and decision speed dropped. We moved to embedded data leads with a light central architecture layer and it worked much better.",
        signal: "Marked as helpful",
        createdAt: daysAgo(4),
      },
      {
        id: "reply-dpe-data-teams-2",
        requestId: "request-dpe-data-teams",
        senderId: "isabella-ops-pharma",
        body: "Our problem was not structure alone, it was incentives. Embedded teams worked only after business leaders were measured on data quality and not just local delivery, otherwise everyone optimized for speed and left the mess central to clean up.",
        signal: "Useful perspective",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-dpe-data-teams-3",
        requestId: "request-dpe-data-teams",
        senderId: "victor-commercial",
        body: "Commercial is where embedded has to win in my view because context moves too fast. What we kept central was platform, governance, and vendor control, but not prioritization or business translation.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-dpe-head-ai-1",
        requestId: "request-dpe-head-ai",
        senderId: "anna-digital",
        body: "We over-indexed on academic credibility and ended up with someone who could not move skeptical business leaders. The miss was not technical depth, it was change leadership inside a regulated organization.",
        signal: "Marked as helpful",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-dpe-head-ai-2",
        requestId: "request-dpe-head-ai",
        senderId: "jonas-platform",
        body: "I would still keep scientific seriousness in the brief if the role touches clinical or regulatory workflows. The profile that worked for us had enough depth to challenge vendors, but had already shipped inside a complex operating environment.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-dpe-explainability-1",
        requestId: "request-dpe-explainability",
        senderId: "meera-regops",
        body: "We stopped asking whether the model was explainable in the abstract and started asking whether the decision path could be reconstructed for audit. That shift made the discussion much more practical with quality and regulatory teams.",
        signal: "Marked as helpful",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-dpe-build-buy-1",
        requestId: "request-dpe-build-buy",
        senderId: "marcus-data-pharma",
        body: "We drew the line at core workflow orchestration and metadata because that became our differentiation pain fastest. Everything commodity stayed bought, but we stopped pretending the vendor roadmap would solve our operating model problems.",
        signal: "Useful perspective",
        createdAt: daysAgo(3),
      },
      {
        id: "reply-dpe-build-buy-2",
        requestId: "request-dpe-build-buy",
        senderId: "peter-digital-brand",
        body: "Our biggest regret was building too much around an unstable process. The stack was not the issue, the operating assumptions kept changing, so the custom layer became a monument to last year's design.",
        signal: "Marked as helpful",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-dpe-change-management-1",
        requestId: "request-dpe-change-management",
        senderId: "victor-commercial",
        body: "Year two is where the organization asks whether this is now a program or a way of working. We stalled when the digital team kept owning outcomes that should have moved into the business, which made everything look temporary.",
        signal: "Marked as helpful",
        createdAt: daysAgo(5),
      },
      {
        id: "reply-dpe-change-management-2",
        requestId: "request-dpe-change-management",
        senderId: "sophie-ai-pharma",
        body: "I think most efforts stall because the first wins are too local. They look good in a steering committee, but they do not change incentives or management habits, so the organization quietly reverts.",
        signal: "Useful perspective",
        createdAt: daysAgo(3),
      },
      {
        id: "reply-dpe-change-management-3",
        requestId: "request-dpe-change-management",
        senderId: "anna-digital",
        body: "What reset momentum for us was killing three initiatives publicly and reinvesting in one painful but obvious bottleneck. It changed the tone from portfolio theatre to actual prioritization.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-dpe-board-roi-1",
        requestId: "request-dpe-board-roi",
        senderId: "isabella-ops-pharma",
        body: "We stopped presenting digital as a technology category and framed it as cycle time, quality risk, and operating leverage. Boards were much more responsive once the conversation was about decisions and capacity, not tooling.",
        signal: "Marked as helpful",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-dpe-vendor-governance-1",
        requestId: "request-dpe-vendor-governance",
        senderId: "daniel-gxp",
        body: "We waited too long and ended up with three different validation burdens across overlapping vendors. If governance debt is already visible, the reset usually gets more expensive from here, not cheaper.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-property-occupancy-1",
        requestId: "request-property-occupancy",
        senderId: "nora-leasing",
        body: "We held rate too long last spring because occupancy still looked fine on monthly reporting. What we missed was leasing velocity by week, and by the time concessions went live the traffic problem was already obvious. I would watch lead-to-tour drop-off before headline occupancy.",
        signal: "Marked as helpful",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-property-occupancy-2",
        requestId: "request-property-occupancy",
        senderId: "olivia-turnarounds",
        body: "Concessions were the wrong lever for us. We tightened onsite response times and fixed the units sitting too long between turns, and leasing picked back up without giving rate away. If ops is sloppy, discounts just hide the real issue.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-property-maintenance-1",
        requestId: "request-property-maintenance",
        senderId: "michael-facilities",
        body: "Outsourcing overflow helped only after we got ruthless about what overflow meant. Before that, onsite teams dumped every annoying ticket externally and residents got inconsistent service. We kept emergency and high-trust resident work in-house and outsourced only volume trades.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-property-maintenance-2",
        requestId: "request-property-maintenance",
        senderId: "owner-property",
        body: "Callbacks killed the savings for us. On paper the vendor line looked cheaper; in practice the resident frustration and rework made it more expensive. We only got the model to work when one internal lead owned vendor quality like it was an internal team.",
        signal: "Marked as helpful",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-investments-sizing-1",
        requestId: "request-investments-sizing",
        senderId: "rachel-public",
        body: "We were right on the company and wrong on the time horizon, and the position size turned a good idea into a painful quarter. Now if the path is real but messy, we buy the right to be right later instead of trying to win immediately.",
        signal: "Marked as helpful",
        createdAt: daysAgo(3),
      },
      {
        id: "reply-investments-sizing-2",
        requestId: "request-investments-sizing",
        senderId: "irina-credit",
        body: "High conviction is not the same as clean downside. We under-sized a distressed credit trade everyone else hated because the legal recovery path was better than the mark suggested. The restraint mattered because conviction without liquidity room is just ego.",
        signal: "Useful perspective",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-investments-committee-1",
        requestId: "request-investments-committee",
        senderId: "devon-private",
        body: "The thing that changed committee for us was not one more slide, it was showing what had to be true for the thesis to fail. Once the downside was explicit, the debate got sharper and people stopped hiding behind 'timing concerns.'",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-dogs-reactivity-1",
        requestId: "request-dogs-reactivity",
        senderId: "harper-reactivity",
        body: "Calmer owners beat cleaner mechanics almost every time in my reactive cases. We had owners doing technically decent work but escalating the dog with their own tension. The cases started moving only when we coached the human harder than the dog for two weeks.",
        signal: "Marked as helpful",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-dogs-reactivity-2",
        requestId: "request-dogs-reactivity",
        senderId: "tessa-workingdogs",
        body: "I would still fix mechanics early because stressed owners default to whatever is simplest under pressure. If the leash handling and session structure are messy, the owner never gets enough reps to build calm anyway. The sequence matters more than the debate.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-dogs-puppy-1",
        requestId: "request-dogs-puppy",
        senderId: "leo-puppy",
        body: "The cases I push harder on are not the loud puppies, it is the ones rehearsing avoidance and disengagement early. Chaos is normal. Repeated withdrawal around novelty is the thing I regret under-calling.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-music-vocals-1",
        requestId: "request-music-vocals",
        senderId: "kai-mixing",
        body: "We tuned the life out of a chorus last month and everyone knew it, but too late. What fixed it was leaving the edges in on the doubles and only tightening the lead where the note actually broke the listener's attention. Clean is not the same as convincing.",
        signal: "Marked as helpful",
        createdAt: daysAgo(3),
      },
      {
        id: "reply-music-vocals-2",
        requestId: "request-music-vocals",
        senderId: "ayumi-mastering",
        body: "If the rough has urgency and the polished version does not, the problem is usually not mastering or loudness. It is that too many tiny 'fixes' removed the phrasing choices that made the take human. I would keep one rough vocal in the session as a reference and punish every edit against that.",
        signal: "Useful perspective",
        createdAt: daysAgo(2),
      },
      {
        id: "reply-music-mix-revisions-1",
        requestId: "request-music-mix-revisions",
        senderId: "owner-music",
        body: "Round eight is no longer a mix problem, it is a boundary problem. The best reset I found was sending two paths: final revision inside scope, or a fresh revision block with a new fee. The relationship usually improves once the project has an edge again.",
        signal: "Useful perspective",
        createdAt: daysAgo(1),
      },
      {
        id: "reply-music-sync-1",
        requestId: "request-music-sync",
        senderId: "elena-sync",
        body: "Tracks started placing for us when we stopped treating sync notes as creative compromise. Shorter intros, cleaner edit points, and fewer decorative transitions made editors trust the record immediately. Well-produced is not enough if nobody can cut picture to it fast.",
        signal: "Marked as helpful",
        createdAt: daysAgo(1),
      },
    ],
  });

  await prisma.introduction.createMany({
    data: [
      {
        id: "intro-pending-leo",
        requestId: "request-guest-main",
        connectorId: "nina-investor",
        targetUserId: "leo-operator",
        note: "Leo is actively meeting Berlin fintech operators this month.",
        status: "pending",
        createdAt: daysAgo(1),
      },
      {
        id: "intro-accepted-nina",
        requestId: "request-guest-main",
        connectorId: "temp-user",
        targetUserId: "nina-investor",
        note: "Nina can help with Warsaw fintech operator circles.",
        status: "accepted",
        acceptedAt: daysAgo(2),
        createdAt: daysAgo(2),
      },
      {
        id: "intro-declined-maya",
        requestId: "request-nina-operators",
        connectorId: "leo-operator",
        targetUserId: "maya-founder",
        note: "Maya has context on infra founders entering Europe.",
        status: "declined",
        createdAt: daysAgo(6),
      },
      {
        id: "intro-sara-pending",
        requestId: "request-sara-hiring",
        connectorId: "julia-ops",
        targetUserId: "waitlist-user-01",
        note: "I know one strong operator already mentoring product leaders in Warsaw.",
        status: "pending",
        createdAt: daysAgo(1),
      },
    ],
  });

  await prisma.conversation.create({
    data: {
      id: "conversation-accepted-nina",
      introId: "intro-accepted-nina",
      groupId: "group-founders",
      kind: ConversationKind.introduction,
      participantOneId: "guest-user",
      participantTwoId: "nina-investor",
    },
  });

  await prisma.message.createMany({
    data: [
      {
        id: "message-guest-1",
        conversationId: "conversation-accepted-nina",
        senderId: "guest-user",
        body: "Thanks for accepting the intro. I would love to compare notes on Berlin finance hires.",
        createdAt: daysAgo(2),
      },
      {
        id: "message-nina-1",
        conversationId: "conversation-accepted-nina",
        senderId: "nina-investor",
        body: "Happy to help. Send over the context and I can point you to two strong operators.",
        createdAt: daysAgo(2),
      },
    ],
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
